name: Python CI

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Show environment
        run: echo "Application environment is ${{ vars.APP_ENV }}" 
      
      - name: Use demo secret
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          echo "Secret is available to this step"
          echo "Secret length: ${#DEMO_SECRET}"  
      - name: Run application
        run: python app.py
